CREATE TABLE APP_USER
(
    ID       BIGSERIAL NOT NULL,
    USERNAME VARCHAR(255) UNIQUE,
    EMAIL    VARCHAR(255) UNIQUE,
    PASSWORD VARCHAR(255),
    ROLE     VARCHAR(255),
    FULLNAME VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE EXPENSE
(
    ID           BIGSERIAL NOT NULL,
    CATEGORY     VARCHAR(255),
    DESCRIPTION  VARCHAR(255),
    AMOUNT       DOUBLE PRECISION,
    EXPENSE_TIME TIMESTAMP WITHOUT TIME ZONE,
    EMAIL        VARCHAR(255) REFERENCES APP_USER (EMAIL),
    PRIMARY KEY (ID)
);

CREATE TABLE OAUTH2_AUTHORIZED_CLIENT
(
    CLIENT_REGISTRATION_ID  VARCHAR(100)                            NOT NULL,
    PRINCIPAL_NAME          VARCHAR(200)                            NOT NULL,
    ACCESS_TOKEN_TYPE       VARCHAR(100)                            NOT NULL,
    ACCESS_TOKEN_VALUE      TEXT                                    NOT NULL,
    ACCESS_TOKEN_ISSUED_AT  TIMESTAMP                               NOT NULL,
    ACCESS_TOKEN_EXPIRES_AT TIMESTAMP                               NOT NULL,
    ACCESS_TOKEN_SCOPES     VARCHAR(1000) DEFAULT NULL,
    REFRESH_TOKEN_VALUE     TEXT          DEFAULT NULL,
    REFRESH_TOKEN_ISSUED_AT TIMESTAMP     DEFAULT NULL,
    CREATED_AT              TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (CLIENT_REGISTRATION_ID, PRINCIPAL_NAME)
);