spring:
  application:
    name: expense360-oauth

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:client-secret}
  sql:
    init:
      mode: always


