database: postgres
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/expense_management}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
  sql:
    init:
      schema-locations: classpath*:db/${database}/schema.sql
